repos:
  - repo: local
    hooks:
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint
        language: system
        types: [swift]
      - id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        args: ['--lint']
        language: system
        types: [swift]

