name: Build FlockSDK (iOS)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-15  # Uses macOS with Xcode 15.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode 16.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Show available destinations (for debugging)
        run: xcodebuild -showdestinations -scheme FlockSDK -sdk iphonesimulator

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -scheme FlockSDK \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
            clean build \
            CODE_SIGNING_ALLOWED=NO