name: Build FlockSDK (iOS)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest  # Uses macOS with Xcode 15.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Show available destinations (for debugging)
        run: xcodebuild -showdestinations -scheme FlockSDK -sdk iphonesimulator

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -scheme FlockSDK \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
            clean build \
            CODE_SIGNING_ALLOWED=NO